# Generated by Django 5.2.4 on 2025-08-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_subject_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='student_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
