# Generated by Django 5.2.4 on 2025-07-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_timetable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timetable',
            name='color',
            field=models.CharField(choices=[('#FF5733', 'Red'), ('#33FF57', 'Green'), ('#3357FF', 'Blue'), ('#F333FF', 'Purple'), ('#FF33F3', 'Pink'), ('#33FFF5', 'Teal')], default='#3357FF', max_length=7),
        ),
    ]
