# Generated by Django 5.2.4 on 2025-07-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='color',
        ),
        migrations.AlterField(
            model_name='timetable',
            name='section',
            field=models.CharField(max_length=10),
        ),
    ]
