# Generated by Django 5.2.4 on 2025-07-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_remove_timetable_color_alter_timetable_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={},
        ),
        migrations.AddField(
            model_name='timetable',
            
            name='color',
            field=models.CharField(choices=[('#FF5733', 'Red'), ('#33FF57', 'Green'), ('#3357FF', 'Blue'), ('#F333FF', 'Purple'), ('#FF33F3', 'Pink'), ('#33FFF5', 'Teal')], default='#3357FF', max_length=7),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('day', 'start_time', 'student_class', 'section')},
        ),
    ]
