# Generated by Django 5.2.4 on 2025-07-29 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_timetable_options_timetable_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['day', 'start_time']},
        ),
    ]
