# Generated by Django 5.2.4 on 2025-07-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_timetable_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exam',
            name='max_two_exams_per_teacher_per_day',
        ),
        migrations.AddField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='section',
            field=models.CharField(default='A', max_length=10),
        ),
    ]
