# Generated by Django 5.2.4 on 2025-07-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_image',
            field=models.ImageField(blank=True, null=True, upload_to='student/'),
        ),
    ]
