# Generated by Django 5.2.4 on 2025-07-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
