# Generated by Django 5.2.4 on 2025-07-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0002_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='yWrhrKfspvM1WoYSQI6eN8p9HRxV5ztm', editable=False, max_length=32),
        ),
    ]
