# Generated by Django 5.2.4 on 2025-08-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='4xZvfEDKvLr9yTNIYOkXVYZdEPNTbZtW', editable=False, max_length=32),
        ),
    ]
