# Generated by Django 5.2.4 on 2025-08-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0003_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='AxvTYMJVW2vgYzoYDCCuov7QX3qF7zck', editable=False, max_length=32),
        ),
    ]
