# Generated by Django 5.2.4 on 2025-08-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0003_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='VUU06Lg5UonmcEks2ZuPSjrkPmifxIkI', editable=False, max_length=32),
        ),
    ]
