# Generated by Django 5.2.4 on 2025-07-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0003_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='f1gqVm0hpHSOkhHTLn7czqPKdK7MScs7', editable=False, max_length=32),
        ),
    ]
