# Generated by Django 5.2.4 on 2025-08-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0004_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='cwBOZi42wxqtROvTc05BHA3jlh8eeeOL', editable=False, max_length=32),
        ),
    ]
