# Generated by Django 5.2.4 on 2025-08-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0005_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='VEnrR8OnWTI0XciwOTow4aAMuUo64tdp', editable=False, max_length=32),
        ),
    ]
