# Generated by Django 5.2.4 on 2025-08-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0006_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='oXQg8HCcYEBNoUd8f43lmgVADBqgsMSh', editable=False, max_length=32),
        ),
    ]
