# Generated by Django 5.2.4 on 2025-07-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0007_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='WIWbaXWle2uwB9V7wsptqNkHD0r55Lmr', editable=False, max_length=32),
        ),
    ]
