# Generated by Django 5.2.4 on 2025-08-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0008_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='HFJPXzdZLxFWzDnBmo263aTIfqdFYjQL', editable=False, max_length=32),
        ),
    ]
