# Generated by Django 5.2.4 on 2025-07-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0010_alter_customuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='ifeo34HMm6ZifCpFU8bfbYV2TwKJchQR', editable=False, max_length=32),
        ),
    ]
