# Generated by Django 5.2.4 on 2025-07-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0011_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='kOoB2AAcYWaTiiR4YiJ7fyca3vY5EOxT', editable=False, max_length=32),
        ),
    ]
