# Generated by Django 5.2.4 on 2025-08-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0012_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='9qOfFHBmKs90hzG5UyRWtz1n8zKmlztr', editable=False, max_length=32),
        ),
    ]
