# Generated by Django 5.2.4 on 2025-07-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0012_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='wfNQntCohaxKbWq0GbjVhirhYfjiuXWq', editable=False, max_length=32),
        ),
    ]
