# Generated by Django 5.2.4 on 2025-08-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0013_remove_customuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='eF3biWNBzgl7cnrZCN1H4HuMycl3YDYs', editable=False, max_length=32),
        ),
    ]
