# Generated by Django 5.2.4 on 2025-07-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0015_alter_customuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='V5gZaV128xmBb2SSsCmqouvnTEd8fuiV', editable=False, max_length=32),
        ),
    ]
