# Generated by Django 5.2.4 on 2025-08-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0015_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='7U7xnk866BSmQnlHmGuN8gtrxrv2imXo', editable=False, max_length=32),
        ),
    ]
