# Generated by Django 5.2.4 on 2025-08-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0016_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='Ffn0DieDIV7HuZFGdZDq1ttesQJhmWZB', editable=False, max_length=32),
        ),
    ]
