# Generated by Django 5.2.4 on 2025-07-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0017_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='f8Q4GXJVft65u3VQGSK94PojpnUhoTcT', editable=False, max_length=32),
        ),
    ]
