# Generated by Django 5.2.4 on 2025-07-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0020_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='B0tJvDavyi0KABsX0Ex0wL99MWfwsoKl', editable=False, max_length=32),
        ),
    ]
