# Generated by Django 5.2.4 on 2025-07-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0021_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='oCtRprtWiHJ4BBYPCrhE7xJiOK9htVD5', editable=False, max_length=32),
        ),
    ]
