# Generated by Django 5.2.4 on 2025-07-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0022_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='rpl8Jy2gcqr3LliVYmbMPRK2xMetzOOm', editable=False, max_length=32),
        ),
    ]
