# Generated by Django 5.2.4 on 2025-07-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0024_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='oaTwOol4560tW7W6Z1J5iXE4GGhU7YWK', editable=False, max_length=32),
        ),
    ]
