# Generated by Django 5.2.4 on 2025-07-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0026_alter_passwordresetrequest_token_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='q8yzOUfTLLhVylKSx2WqBT71VGHuCbfz', editable=False, max_length=32),
        ),
    ]
