# Generated by Django 5.2.4 on 2025-07-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0027_customuser_section_customuser_student_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='UBz6B9sfMBMnXVOAYod6GkVvxzLvi4ha', editable=False, max_length=32),
        ),
    ]
