# Generated by Django 5.2.4 on 2025-07-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0028_customuser_department_customuser_joining_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='BRMszaMtO8KmE3itzHfKx1HNB253oitl', editable=False, max_length=32),
        ),
    ]
