# Generated by Django 5.2.4 on 2025-07-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0029_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='hq0oFLHWgOBGve8BtaEroHqsk0GJ8Edc', editable=False, max_length=32),
        ),
    ]
