# Generated by Django 5.2.4 on 2025-07-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0030_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='v6va2qcc42iVIfAamDoCTxssr2Qeexgd', editable=False, max_length=32),
        ),
    ]
