# Generated by Django 5.2.4 on 2025-07-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0031_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='eFLTr1Cne9kWHj5M9ZeuXHGH9AnQLuyj', editable=False, max_length=32),
        ),
    ]
