# Generated by Django 5.2.4 on 2025-07-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0034_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='RqK63zXALWzCMfqa7aP8Vzl6yZTTibFm', editable=False, max_length=32),
        ),
    ]
