# Generated by Django 5.2.4 on 2025-07-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0035_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='6jWP8ghmJnAps3rmPAeJbADqtMoqffM2', editable=False, max_length=32),
        ),
    ]
