# Generated by Django 5.2.4 on 2025-07-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0036_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='eMuo0EOUg30ixvO7mS5GxjufMObNfhJS', editable=False, max_length=32),
        ),
    ]
