# Generated by Django 5.2.4 on 2025-07-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0039_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='mGY0zxvM5Ezlu1ckJtdhaYIihwnXklSS', editable=False, max_length=32),
        ),
    ]
