# Generated by Django 5.2.4 on 2025-07-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0042_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='ynF8pubSlT95nzjbjoPnasWUWo62bHcM', editable=False, max_length=32),
        ),
    ]
