# Generated by Django 5.2.4 on 2025-07-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0043_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='c7jIpK3zIOVTyPtF30xHHuyf4dhYmGyf', editable=False, max_length=32),
        ),
    ]
