# Generated by Django 5.2.4 on 2025-07-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0044_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='SLpIpHpns2DfjGvYWdZpzJjp5a5stJsi', editable=False, max_length=32),
        ),
    ]
