# Generated by Django 5.2.4 on 2025-07-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0046_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='tal0M9OuqJj1H8sraN0GIbyRkAOqE3C6', editable=False, max_length=32),
        ),
    ]
