# Generated by Django 5.2.4 on 2025-07-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0047_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='BzXLzekjcnNSUV4Ro32VITM6RsfTtuxM', editable=False, max_length=32),
        ),
    ]
