# Generated by Django 5.2.4 on 2025-07-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0049_customuser_bio_customuser_specialization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='K6QzalIuz6SOGFmfM1xfViUQC07H0PuZ', editable=False, max_length=32),
        ),
    ]
