# Generated by Django 5.2.4 on 2025-07-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0050_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='nwGB22feb5SigdbzXq3nP2WIxtc3piML', editable=False, max_length=32),
        ),
    ]
