# Generated by Django 5.2.4 on 2025-07-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0051_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='uMpmE8s0DooxwNnG0QunnZVWN9Rno2rU', editable=False, max_length=32),
        ),
    ]
