# Generated by Django 5.2.4 on 2025-07-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0053_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='EPOggfp5wdC7Z4hBya4IYPBCIG1eYIu1', editable=False, max_length=32),
        ),
    ]
