# Generated by Django 5.2.4 on 2025-07-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0054_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='hgqYIRcJ5iGx3KR8WD6Mp6BpeLDZwRRh', editable=False, max_length=32),
        ),
    ]
