# Generated by Django 5.2.4 on 2025-07-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0056_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='Ve78SeJYcB0Q1nANYX0zKI6WsXNfWVsz', editable=False, max_length=32),
        ),
    ]
