# Generated by Django 5.2.4 on 2025-07-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0057_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='b6zgVNVTOH8WlaBvYlqYwbLDcL0WTD9n', editable=False, max_length=32),
        ),
    ]
