# Generated by Django 5.2.4 on 2025-07-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0058_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='yIG7MaXlYIQiU2t5etG22v0KkuR5kY9w', editable=False, max_length=32),
        ),
    ]
