# Generated by Django 5.2.4 on 2025-07-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0059_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='u3XNwz0QeBl2Q0bbYyKXdD6t7ggfW1nK', editable=False, max_length=32),
        ),
    ]
