# Generated by Django 5.2.4 on 2025-07-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0061_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='eopbQT3hwiID5ObA52tVzTZ02OkydbZw', editable=False, max_length=32),
        ),
    ]
