# Generated by Django 5.2.4 on 2025-07-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0063_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='LYWccFsLF2VaUPNc7b7WsWXa2gvq4FAZ', editable=False, max_length=32),
        ),
    ]
