# Generated by Django 5.2.4 on 2025-07-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0065_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='BAEdeiIlWwOWVo0dTL9TDxq5B4SqL6HK', editable=False, max_length=32),
        ),
    ]
