# Generated by Django 5.2.4 on 2025-07-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0066_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='KRvHOpwpIix72YzXUthqLUscuF62webG', editable=False, max_length=32),
        ),
    ]
