# Generated by Django 5.2.4 on 2025-07-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0069_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='44xU94r3r2DsGlHgk1eDVXPDnN1de9Nv', editable=False, max_length=32),
        ),
    ]
