# Generated by Django 5.2.4 on 2025-07-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0070_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='7k2ZVuhRO3DwOZ7BrjM6nAH1kEGJOVNF', editable=False, max_length=32),
        ),
    ]
